# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fridge.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'fridge.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x66ridge.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x0c\x63ommon.proto\"\xc0\x01\n\nFridgeInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12!\n\x06\x64_type\x18\x02 \x01(\x0e\x32\x11.proto.DeviceType\x12\x13\n\x0btemperature\x18\x03 \x01(\x01\x12\x13\n\x0b\x64oor_closed\x18\x04 \x01(\x08\x12\x1f\n\x04type\x18\x05 \x01(\x0e\x32\x11.proto.FridgeType\x12 \n\x13\x66reezer_temperature\x18\x06 \x01(\x01H\x00\x88\x01\x01\x42\x16\n\x14_freezer_temperature\"0\n\nFridgeList\x12\"\n\x07\x64\x65vices\x18\x01 \x03(\x0b\x32\x11.proto.FridgeInfo\"r\n\x15SetTemperatureRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0btemperature\x18\x02 \x01(\x01\x12 \n\x13\x66reezer_temperature\x18\x03 \x01(\x01H\x00\x88\x01\x01\x42\x16\n\x14_freezer_temperature\":\n\x16SetTemperatureResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t*.\n\nFridgeType\x12\x0e\n\nNO_FREEZER\x10\x00\x12\x10\n\x0cWITH_FREEZER\x10\x01\x32\xcb\x01\n\x06\x46ridge\x12\x38\n\x0bListFridges\x12\x16.google.protobuf.Empty\x1a\x11.proto.FridgeList\x12M\n\x0eSetTemperature\x12\x1c.proto.SetTemperatureRequest\x1a\x1d.proto.SetTemperatureResponse\x12\x38\n\rGetFridgeInfo\x12\x14.proto.DeviceRequest\x1a\x11.proto.FridgeInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fridge_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FRIDGETYPE']._serialized_start=487
  _globals['_FRIDGETYPE']._serialized_end=533
  _globals['_FRIDGEINFO']._serialized_start=67
  _globals['_FRIDGEINFO']._serialized_end=259
  _globals['_FRIDGELIST']._serialized_start=261
  _globals['_FRIDGELIST']._serialized_end=309
  _globals['_SETTEMPERATUREREQUEST']._serialized_start=311
  _globals['_SETTEMPERATUREREQUEST']._serialized_end=425
  _globals['_SETTEMPERATURERESPONSE']._serialized_start=427
  _globals['_SETTEMPERATURERESPONSE']._serialized_end=485
  _globals['_FRIDGE']._serialized_start=536
  _globals['_FRIDGE']._serialized_end=739
# @@protoc_insertion_point(module_scope)
