# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import common_pb2 as common__pb2
import fridge_pb2 as fridge__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in fridge_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FridgeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListFridges = channel.unary_unary(
                '/proto.Fridge/ListFridges',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=fridge__pb2.FridgeList.FromString,
                _registered_method=True)
        self.SetTemperature = channel.unary_unary(
                '/proto.Fridge/SetTemperature',
                request_serializer=fridge__pb2.SetTemperatureRequest.SerializeToString,
                response_deserializer=fridge__pb2.SetTemperatureResponse.FromString,
                _registered_method=True)
        self.GetFridgeInfo = channel.unary_unary(
                '/proto.Fridge/GetFridgeInfo',
                request_serializer=common__pb2.DeviceRequest.SerializeToString,
                response_deserializer=fridge__pb2.FridgeInfo.FromString,
                _registered_method=True)


class FridgeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListFridges(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTemperature(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFridgeInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FridgeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListFridges': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFridges,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=fridge__pb2.FridgeList.SerializeToString,
            ),
            'SetTemperature': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTemperature,
                    request_deserializer=fridge__pb2.SetTemperatureRequest.FromString,
                    response_serializer=fridge__pb2.SetTemperatureResponse.SerializeToString,
            ),
            'GetFridgeInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFridgeInfo,
                    request_deserializer=common__pb2.DeviceRequest.FromString,
                    response_serializer=fridge__pb2.FridgeInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.Fridge', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.Fridge', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Fridge(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListFridges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.Fridge/ListFridges',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            fridge__pb2.FridgeList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetTemperature(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.Fridge/SetTemperature',
            fridge__pb2.SetTemperatureRequest.SerializeToString,
            fridge__pb2.SetTemperatureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFridgeInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.Fridge/GetFridgeInfo',
            common__pb2.DeviceRequest.SerializeToString,
            fridge__pb2.FridgeInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
