# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: light.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'light.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0blight.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x0c\x63ommon.proto\"\xaf\x01\n\tLightInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12!\n\x06\x64_type\x18\x02 \x01(\x0e\x32\x11.proto.DeviceType\x12\r\n\x05is_on\x18\x03 \x01(\x08\x12\x1e\n\x04type\x18\x04 \x01(\x0e\x32\x10.proto.LightType\x12\x12\n\x05\x63olor\x18\x05 \x01(\tH\x00\x88\x01\x01\x12\x17\n\nbrightness\x18\x06 \x01(\x01H\x01\x88\x01\x01\x42\x08\n\x06_colorB\r\n\x0b_brightness\".\n\tLightList\x12!\n\x07\x64\x65vices\x18\x01 \x03(\x0b\x32\x10.proto.LightInfo\"\x1b\n\rTurnOnRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x1c\n\x0eTurnOffRequest\x12\n\n\x02id\x18\x01 \x01(\t\",\n\x0fSetColorRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x63olor\x18\x02 \x01(\t\"6\n\x14SetBrightnessRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nbrightness\x18\x02 \x01(\x01\"1\n\rLightResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t*.\n\tLightType\x12\n\n\x06NORMAL\x10\x00\x12\x07\n\x03RGB\x10\x01\x12\x0c\n\x08\x44IMMABLE\x10\x02\x32\xe3\x02\n\x05Light\x12\x34\n\x06TurnOn\x12\x14.proto.TurnOnRequest\x1a\x14.proto.LightResponse\x12\x36\n\x07TurnOff\x12\x15.proto.TurnOffRequest\x1a\x14.proto.LightResponse\x12\x36\n\x0cGetLightInfo\x12\x14.proto.DeviceRequest\x1a\x10.proto.LightInfo\x12\x36\n\nListLights\x12\x16.google.protobuf.Empty\x1a\x10.proto.LightList\x12\x38\n\x08SetColor\x12\x16.proto.SetColorRequest\x1a\x14.proto.LightResponse\x12\x42\n\rSetBrightness\x12\x1b.proto.SetBrightnessRequest\x1a\x14.proto.LightResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'light_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LIGHTTYPE']._serialized_start=503
  _globals['_LIGHTTYPE']._serialized_end=549
  _globals['_LIGHTINFO']._serialized_start=66
  _globals['_LIGHTINFO']._serialized_end=241
  _globals['_LIGHTLIST']._serialized_start=243
  _globals['_LIGHTLIST']._serialized_end=289
  _globals['_TURNONREQUEST']._serialized_start=291
  _globals['_TURNONREQUEST']._serialized_end=318
  _globals['_TURNOFFREQUEST']._serialized_start=320
  _globals['_TURNOFFREQUEST']._serialized_end=348
  _globals['_SETCOLORREQUEST']._serialized_start=350
  _globals['_SETCOLORREQUEST']._serialized_end=394
  _globals['_SETBRIGHTNESSREQUEST']._serialized_start=396
  _globals['_SETBRIGHTNESSREQUEST']._serialized_end=450
  _globals['_LIGHTRESPONSE']._serialized_start=452
  _globals['_LIGHTRESPONSE']._serialized_end=501
  _globals['_LIGHT']._serialized_start=552
  _globals['_LIGHT']._serialized_end=907
# @@protoc_insertion_point(module_scope)
