# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import common_pb2 as common__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import light_pb2 as light__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in light_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LightStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TurnOn = channel.unary_unary(
                '/proto.Light/TurnOn',
                request_serializer=light__pb2.TurnOnRequest.SerializeToString,
                response_deserializer=light__pb2.LightResponse.FromString,
                _registered_method=True)
        self.TurnOff = channel.unary_unary(
                '/proto.Light/TurnOff',
                request_serializer=light__pb2.TurnOffRequest.SerializeToString,
                response_deserializer=light__pb2.LightResponse.FromString,
                _registered_method=True)
        self.GetLightInfo = channel.unary_unary(
                '/proto.Light/GetLightInfo',
                request_serializer=common__pb2.DeviceRequest.SerializeToString,
                response_deserializer=light__pb2.LightInfo.FromString,
                _registered_method=True)
        self.ListLights = channel.unary_unary(
                '/proto.Light/ListLights',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=light__pb2.LightList.FromString,
                _registered_method=True)
        self.SetColor = channel.unary_unary(
                '/proto.Light/SetColor',
                request_serializer=light__pb2.SetColorRequest.SerializeToString,
                response_deserializer=light__pb2.LightResponse.FromString,
                _registered_method=True)
        self.SetBrightness = channel.unary_unary(
                '/proto.Light/SetBrightness',
                request_serializer=light__pb2.SetBrightnessRequest.SerializeToString,
                response_deserializer=light__pb2.LightResponse.FromString,
                _registered_method=True)


class LightServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TurnOn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TurnOff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLightInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListLights(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetColor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetBrightness(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LightServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TurnOn': grpc.unary_unary_rpc_method_handler(
                    servicer.TurnOn,
                    request_deserializer=light__pb2.TurnOnRequest.FromString,
                    response_serializer=light__pb2.LightResponse.SerializeToString,
            ),
            'TurnOff': grpc.unary_unary_rpc_method_handler(
                    servicer.TurnOff,
                    request_deserializer=light__pb2.TurnOffRequest.FromString,
                    response_serializer=light__pb2.LightResponse.SerializeToString,
            ),
            'GetLightInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLightInfo,
                    request_deserializer=common__pb2.DeviceRequest.FromString,
                    response_serializer=light__pb2.LightInfo.SerializeToString,
            ),
            'ListLights': grpc.unary_unary_rpc_method_handler(
                    servicer.ListLights,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=light__pb2.LightList.SerializeToString,
            ),
            'SetColor': grpc.unary_unary_rpc_method_handler(
                    servicer.SetColor,
                    request_deserializer=light__pb2.SetColorRequest.FromString,
                    response_serializer=light__pb2.LightResponse.SerializeToString,
            ),
            'SetBrightness': grpc.unary_unary_rpc_method_handler(
                    servicer.SetBrightness,
                    request_deserializer=light__pb2.SetBrightnessRequest.FromString,
                    response_serializer=light__pb2.LightResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.Light', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.Light', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Light(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TurnOn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.Light/TurnOn',
            light__pb2.TurnOnRequest.SerializeToString,
            light__pb2.LightResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TurnOff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.Light/TurnOff',
            light__pb2.TurnOffRequest.SerializeToString,
            light__pb2.LightResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLightInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.Light/GetLightInfo',
            common__pb2.DeviceRequest.SerializeToString,
            light__pb2.LightInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListLights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.Light/ListLights',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            light__pb2.LightList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetColor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.Light/SetColor',
            light__pb2.SetColorRequest.SerializeToString,
            light__pb2.LightResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetBrightness(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.Light/SetBrightness',
            light__pb2.SetBrightnessRequest.SerializeToString,
            light__pb2.LightResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
