# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: temperature.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'temperature.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11temperature.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x0c\x63ommon.proto\"N\n\x08TempInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12!\n\x06\x64_type\x18\x02 \x01(\x0e\x32\x11.proto.DeviceType\x12\x13\n\x0btemperature\x18\x03 \x01(\x01\",\n\x08TempList\x12 \n\x07\x64\x65vices\x18\x01 \x03(\x0b\x32\x0f.proto.TempInfo2~\n\x0bTemperature\x12\x36\n\x0bListDevices\x12\x16.google.protobuf.Empty\x1a\x0f.proto.TempList\x12\x37\n\x0eGetTemperature\x12\x14.proto.DeviceRequest\x1a\x0f.proto.TempInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'temperature_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEMPINFO']._serialized_start=71
  _globals['_TEMPINFO']._serialized_end=149
  _globals['_TEMPLIST']._serialized_start=151
  _globals['_TEMPLIST']._serialized_end=195
  _globals['_TEMPERATURE']._serialized_start=197
  _globals['_TEMPERATURE']._serialized_end=323
# @@protoc_insertion_point(module_scope)
